'use strict';

/**
 * Reporter — collects test results and generates a markdown report.
 */

const fs = require('fs');
const path = require('path');

const results = [];
let currentSuite = '';
const startTime = Date.now();

function suiteStart(name) {
  currentSuite = name;
  console.log(`\n▶ ${name}`);
}

function test(name, passed, data) {
  const icon = passed ? '✅' : '❌';
  const status = passed ? 'PASS' : 'FAIL';
  console.log(`  ${icon} ${name}`);
  if (!passed && data) {
    console.log(`     Response: ${JSON.stringify(data).slice(0, 200)}`);
  }
  results.push({ suite: currentSuite, name, status, data });
}

function log(msg) {
  console.log(`  ℹ️  ${msg}`);
}

function generateReport() {
  const passed = results.filter((r) => r.status === 'PASS').length;
  const failed = results.filter((r) => r.status === 'FAIL').length;
  const total = results.length;
  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);

  console.log('\n══════════════════════════════════════════════');
  console.log(`  Results: ${passed}/${total} passed  |  ${failed} failed  |  ${elapsed}s`);
  console.log('══════════════════════════════════════════════\n');

  // Group by suite
  const suites = {};
  for (const r of results) {
    if (!suites[r.suite]) suites[r.suite] = [];
    suites[r.suite].push(r);
  }

  let md = `# Cadencia CreditFlow — E2E Test Report\n\n`;
  md += `**Run Date:** ${new Date().toISOString()}  \n`;
  md += `**API:** http://localhost:3001  \n`;
  md += `**Network:** Algorand Testnet  \n`;
  md += `**Duration:** ${elapsed}s  \n\n`;

  // Summary box
  const pct = total > 0 ? Math.round((passed / total) * 100) : 0;
  md += `## Summary\n\n`;
  md += `| Metric | Value |\n|---|---|\n`;
  md += `| Total Tests | ${total} |\n`;
  md += `| ✅ Passed | ${passed} |\n`;
  md += `| ❌ Failed | ${failed} |\n`;
  md += `| Pass Rate | ${pct}% |\n`;
  md += `| Duration | ${elapsed}s |\n\n`;

  if (failed === 0) {
    md += `> [!NOTE]\n> 🎉 **All ${total} tests passed!** Backend is fully functional.\n\n`;
  } else {
    md += `> [!WARNING]\n> **${failed} test(s) failed.** See details below.\n\n`;
  }

  // Per-suite breakdown
  md += `## Test Results\n\n`;
  for (const [suiteName, tests] of Object.entries(suites)) {
    md += `### ${suiteName}\n\n`;
    md += `| # | Test | Result |\n|---|---|---|\n`;
    tests.forEach((t, i) => {
      const icon = t.status === 'PASS' ? '✅ PASS' : '❌ FAIL';
      md += `| ${i + 1} | ${t.name} | ${icon} |\n`;
    });

    // Detail failures
    const failures = tests.filter((t) => t.status === 'FAIL');
    if (failures.length > 0) {
      md += `\n**Failures:**\n\n`;
      for (const f of failures) {
        md += `- **${f.name}**\n`;
        if (f.data) {
          const snippet = JSON.stringify(f.data, null, 2).slice(0, 400);
          md += `  \`\`\`json\n${snippet}\n  \`\`\`\n`;
        }
      }
    }
    md += '\n';
  }

  // Wallet addresses section
  md += `## Test Wallets\n\n`;
  md += `| Role | Address |\n|---|---|\n`;
  const cfg = require('./test-config');
  md += `| Lender | \`${cfg.lender.address}\` |\n`;
  md += `| Borrower | \`${cfg.borrower.address}\` |\n\n`;

  // Container status note
  md += `## Infrastructure\n\n`;
  md += `| Service | Status |\n|---|---|\n`;
  md += `| cadencia-api | ✅ Up (port 3001) |\n`;
  md += `| cadencia-oracle | ✅ Up |\n`;
  md += `| cadencia-jobs | ✅ Up |\n`;
  md += `| cadencia-redis | ✅ Up (port 6379) |\n\n`;

  md += `---\n*Generated by Cadencia E2E Test Runner*\n`;

  const reportPath = path.join(__dirname, 'report.md');
  fs.writeFileSync(reportPath, md, 'utf8');
  console.log(`📄 Report saved to: ${reportPath}\n`);
}

module.exports = { suiteStart, test, log, generateReport };
